import './crawler_ability';
import './crawler_characteristic';
import './crawler_egg_group';
import './crawler_gender';
import './crawler_growth_rate';
import './crawler_nature';
import './crawler_pokeathlon_stat';
import './crawler_pokemon_color';
import './crawler_pokemon_habitat';
